Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  config.vm.define "loadbalancer" do |lb|
    lb.vm.synced_folder ".", "/vagrant", disabled: true
    lb.vm.hostname = "loadbalancer"
    lb.vm.network "private_network", ip:"10.0.26.100"
    lb.vm.network "forwarded_port", guest: 80, host: 80, host_ip: "127.0.0.1"
    lb.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "loadbalancer"
    end
    lb.vm.provision "shell", path: "shell/iptables.sh"
    lb.vm.provision "shell", inline: "service network restart"
    lb.vm.provision "shell", inline: "sed -i '/PasswordAuthentication/s/no/yes/' /etc/ssh/sshd_config"
    lb.vm.provision "shell", inline: "service sshd restart"
end

N = 2
  (1..N).each do |i|
    config.vm.define "webserver0#{i}" do |web|
      web.vm.network "private_network", ip:"10.0.26.10#{i}"
      web.vm.hostname = "webserver0#{i}"
      web.vm.box = "centos/7"
      web.vm.synced_folder ".", "/vagrant", disabled: true
      web.vm.box_check_update = false
      web.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.name = "webserver0#{i}"
      end
      web.vm.provision "shell", path: "shell/iptables.sh"
      web.vm.provision "shell", inline: "service network restart"
      web.vm.provision "shell", inline: "sed -i '/PasswordAuthentication/s/no/yes/' /etc/ssh/sshd_config"
      web.vm.provision "shell", inline: "service sshd restart"
  end
end

  config.vm.define "mgmt" do |mgmt|
      mgmt.vm.network "private_network", ip:"10.0.26.200"
      mgmt.vm.hostname = "mgmt"
      mgmt.vm.box = "centos/7"
      mgmt.vm.synced_folder ".", "/vagrant", disabled: true
      mgmt.vm.box_check_update = false
      mgmt.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.name = "mgmt"
      end
      mgmt.vm.provision "shell", inline: "service network restart"
      mgmt.vm.provision "shell", inline: "sed -i '/PasswordAuthentication/s/no/yes/' /etc/ssh/sshd_config"
      mgmt.vm.provision "shell", inline: "service sshd restart"
      mgmt.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
      mgmt.vm.provision "file", source: "provision", destination: "/home/vagrant/"
      mgmt.vm.provision "shell", path: "shell/ansible-setup.sh"
  end
end